databases:
  - name: djangotest
    plan: free
    databaseName: supercoins_stage
    user: vkustov

services:
  - type: web
    plan: free
    name: supercoins_websrv_staging
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn mysite.asgi:application -k uvicorn.workers.UvicornWorker"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: djangotest
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4